// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkxv-VgCG2wQio8N1DbLbQK7HCQXMH16Q',
    appId: '1:773664446418:web:9b4ea354e581f0d37f5a0b',
    messagingSenderId: '773664446418',
    projectId: 'onceuponayard',
    authDomain: 'onceuponayard.firebaseapp.com',
    storageBucket: 'onceuponayard.firebasestorage.app',
    measurementId: 'G-4MSP3R2K0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJNxjUxkTW8NAQPsMxuw7j56KkH50kTuo',
    appId: '1:773664446418:android:dd8f8cce5da386867f5a0b',
    messagingSenderId: '773664446418',
    projectId: 'onceuponayard',
    storageBucket: 'onceuponayard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0EktzeRsoaHqa9iiDfzi6wct75OwaL5E',
    appId: '1:773664446418:ios:a8d528830d80f0937f5a0b',
    messagingSenderId: '773664446418',
    projectId: 'onceuponayard',
    storageBucket: 'onceuponayard.firebasestorage.app',
    androidClientId: '773664446418-v8dvg1ljh44j27ta98m5cuf23p0f8cmj.apps.googleusercontent.com',
    iosClientId: '773664446418-1vho2bo195vhd9otbkrs15ths4mpa34j.apps.googleusercontent.com',
    iosBundleId: 'com.example.onceUponAYard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0EktzeRsoaHqa9iiDfzi6wct75OwaL5E',
    appId: '1:773664446418:ios:a8d528830d80f0937f5a0b',
    messagingSenderId: '773664446418',
    projectId: 'onceuponayard',
    storageBucket: 'onceuponayard.firebasestorage.app',
    androidClientId: '773664446418-v8dvg1ljh44j27ta98m5cuf23p0f8cmj.apps.googleusercontent.com',
    iosClientId: '773664446418-1vho2bo195vhd9otbkrs15ths4mpa34j.apps.googleusercontent.com',
    iosBundleId: 'com.example.onceUponAYard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkxv-VgCG2wQio8N1DbLbQK7HCQXMH16Q',
    appId: '1:773664446418:web:fdca7925896ba2da7f5a0b',
    messagingSenderId: '773664446418',
    projectId: 'onceuponayard',
    authDomain: 'onceuponayard.firebaseapp.com',
    storageBucket: 'onceuponayard.firebasestorage.app',
    measurementId: 'G-TSVRF4WE4M',
  );

}