import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'services/auth_services.dart';
import 'screens/auth_screen.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'screens/main_layout.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform
  );
  // <--- ADD THIS BLOCK --->
  await FirebaseAppCheck.instance.activate(
    // Web Provider
    webProvider: ReCaptchaV3Provider('recaptcha-v3-site-key'),
    // Android Provider
    androidProvider: AndroidProvider.debug, // Use .debug for emulators, .playIntegrity for release
    // iOS Provider
    appleProvider: AppleProvider.appAttest, // or .deviceCheck
  );
  // <--- END BLOCK --->
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fruit Neighbor',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        primaryColor: const Color(0xFF228B22),
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF228B22)),
        fontFamily: 'Nunito', // Ensure you added google_fonts if using this
      ),
      // THE GATEKEEPER LOGIC
      home: StreamBuilder(
        stream: AuthService().user,
        builder: (context, snapshot) {
          // 1. If waiting for connection, show splash
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(body: Center(child: CircularProgressIndicator()));
          }
          
          // 2. If User exists -> Home
          if (snapshot.hasData) {
           return const MainLayout();
          }
          
          // 3. Otherwise -> Login
          return const AuthScreen();
        },
      ),
    );
  }
}